### PR TITLE
feat: Add how to install javascript Apify client

### PR DESCRIPTION
**Pull request by webrdaniel**

### CODE REVIEW

**Review by B4nan — CHANGES_REQUESTED** [review]
you need to update the next version too, this is just a version snapshot

https://github.com/apify/apify-client-js/blob/master/docs/index.md

i would also generally discourage the prose wrap (line breaks in markdown), but that's something that should be enforced via linter on the whole docs (we do it in the main docs repo already)

**Review by jbartadev — APPROVED** [review]
Cool.

@B4nan wouldn't be enough to just update the `index.md` file? Do you also need to always update the specific version file?

**Comment by B4nan** [comment]
depends on what you want, but generally nope:
- current stable version is the last versioned one, so https://docs.apify.com/api/client/js/docs is `website/versioned_docs/version-2.8/index.md`
- next version (will be used for creating next stable version snapshot) is at https://docs.apify.com/api/client/js/docs/next `docs/index.md`

so when you update only the next version, its fine, but you wont see any changes in the stable docs (untill we ship new minor version). when you update only the snapshot, your changes will be lost on next minor release (they will only stay in that specific snapshot)

**Review by B4nan — APPROVED** [review]

**Comment by webrdaniel** [comment]
> depends on what you want, but generally nope:
> 
> * current stable version is the last versioned one, so https://docs.apify.com/api/client/js/docs is `website/versioned_docs/version-2.8/index.md`
> * next version (will be used for creating next stable version snapshot) is at https://docs.apify.com/api/client/js/docs/next `docs/index.md`
> 
> so when you update only the next version, its fine, but you wont see any changes in the stable docs (untill we ship new minor version). when you update only the snapshot, your changes will be lost on next minor release (they will only stay in that specific snapshot)

@B4nan Thanks for clarification 😄

**Pull request merged**
