### PR TITLE
feat: Add schema parameter to getOrCreate for kvs, dataset

### PR DESCRIPTION
**Pull request by jirimoravcik**

### CODE REVIEW

**Review by mtrunkat — APPROVED** [review]

**Review by B4nan — APPROVED** [review]

**Comment by jirimoravcik** [comment]
@B4nan Should I bump the package version or something?

**Comment by B4nan** [comment]
right, 2.2.0 is out, so we need a bump 

technically minor one, personally i'd just do a patch as it seems like a small change, will leave it up to you :]

**Comment by jirimoravcik** [comment]
> right, 2.2.0 is out, so we need a bump
> 
> technically minor one, personally i'd just do a patch as it seems like a small change, will leave it up to you :]

Went for 2.2.1, added an entry to the changelog, is it ok like this?

**Comment by B4nan** [comment]
sure, feel free to merge

**Pull request merged**
