### PR TITLE
feat(repo): repository links

### PR DESCRIPTION
**Pull request by drobnikj**

### CODE REVIEW

**Comment by drobnikj** [comment]
@B4nan I'm not sure, but I would expect a redirect in this case. Maybe worth checking if we have somewhere https://apify.com/docs/sdk/apify-client-js/latest

**Comment by B4nan** [comment]
There is apparently one redirect already for the https://apify.com/docs/sdk/apify-client-js/latest -> https://docs.apify.com/sdk/apify-client-js/latest, so ideally that one should be fixed instead of adding another to the chain. Any idea where that might be implemented?

**Review by B4nan — APPROVED** [review]

**Comment by drobnikj** [comment]
@B4nan not sure but just add
/sdk/apify-client-js/latest -> /api/client/js/ should work

**Comment by B4nan** [comment]
Yeah already fixing this.

**Pull request merged**
